### ISSUE TITLE
Dragging from collections in collectionview cells

### ISSUE THREAD

**Issue by wieseljonas** [ice3-software/between-kit#76]
HI thanks for the great framework! I'm struggling with a complex setup.

I have a viewcontroller with a collectionview that has 5 collectionview cells (fullscreen) with collectionviews inside of them.

I can drag subcells from the first 3 tableviews in those cells but when I try to drag subcell form the last two last tabeviews the dragCoordinator doesn't correctly identify these collectionviews. I actually thinks its one of the previous collectionviews

Thanks in advance (I'm on iOS9 coding in Swift)

![simulator screen shot 22 sep 2015 15 58 31](https://cloud.githubusercontent.com/assets/1095469/10020386/dd6ed012-6142-11e5-9f5a-5b575870d530.png)

my view controller

        override func viewDidLoad() {
        super.viewDidLoad()
        automaticallyAdjustsScrollViewInsets = false
        self.pipeLineData = ["Lead":["1","2","3","4","5","6","1","2","3","4","5","6"],"Contact":["A","B","C","D","E","F","1","2","3","4","5","6"],"Meeting":["11","22","33","44","55","66"], "Nego":["1","2","3","4","5","6"],"Deal":["A","B","C","D","E","F"]]
        let layout = CenterCellCollectionViewFlowLayout()
        self.view.backgroundColor = UIColor(rgba: "#6BB9F0")
        layout.itemSize = CGSizeMake(self.view.frame.width - 140, self.view.frame.height-150)
        layout.scrollDirection = .Horizontal
        collectionView = UICollectionView(frame: CGRect(x: 0, y: 64, width: self.view.frame.width, height: self.view.frame.height - 108), collectionViewLayout: layout)
        collectionView.dataSource = self
        collectionView.scrollEnabled = true
        collectionView.backgroundColor = UIColor.clearColor()
        collectionView.bounces = true
        self.view.addSubview(collectionView)
        self.collectionView.registerClass(PipelineStageViewCell.self, forCellWithReuseIdentifier:pipelineCellIndentifier)
        
        for _ in pipeLineData {
            let layout = CenterCellCollectionViewFlowLayout()
            layout.scrollDirection = .Vertical
            layout.itemSize = CGSizeMake(self.view.frame.width - 160, 30)
            let col = UICollectionView(frame: CGRectZero, collectionViewLayout:layout)
            col.backgroundColor = UIColor(rgba: "#F5F5F5")
            col.dataSource = self
            col.delegate = self
            col.registerClass(PipelineDealCell.self, forCellWithReuseIdentifier:pipelineDealIndentifier)
            var insets = col.contentInset
            insets.top = 10
            insets.bottom = 10
            col.contentInset = insets
            self.stepCollection.append(col)
        }
        
        self.dragArena = I3DragArena(superview: self.view , containingCollections: self.stepCollection)
        self.dragCoordinator = I3GestureCoordinator.basicGestureCoordinatorFromViewController(self, withCollections: self.stepCollection, withRecognizer: UILongPressGestureRecognizer())
        self.dragCoordinator.dragDataSource = self
        let renderDelegate = self.dragCoordinator.renderDelegate as! I3BasicRenderDelegate
        renderDelegate.draggingItemOpacity = 0.3

    }
    
    unc collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        if self.isMainCollection(collectionView){
            let cell = collectionView.dequeueReusableCellWithReuseIdentifier(pipelineCellIndentifier, forIndexPath: indexPath) as! PipelineStageViewCell
            cell.setCollectionView(self.stepCollection[indexPath.row])
            cell.stepTitle.text = self.dataForCollectionView(collectionView)[indexPath.row] as? String
            return cell
        } else {
            let cell = collectionView.dequeueReusableCellWithReuseIdentifier(pipelineDealIndentifier, forIndexPath: indexPath) as! PipelineDealCell
            cell.dealData = self.dataForCollectionView(collectionView)[indexPath.row] as! String
            return cell
        }
    }
    
    func dataForCollectionView(collectionView: UIView) -> [AnyObject] {
        var data: [AnyObject]? = nil
        var index = 0
        var isFound = false
        for collection in self.stepCollection {
            if collection == collectionView {
                let key = Array(self.pipeLineData.keys)[index]
                data = self.pipeLineData[key]
                isFound = true
            }
            index++
        }
        if !isFound {
            data = Array(self.pipeLineData.keys)
        }
        return data!
    }
    
    func keyForCollectionView(collectionView: UIView) -> String {
        var index = 0
        for collection in self.stepCollection {
            if collection == collectionView {
                return Array(self.pipeLineData.keys)[index]
            }
            index++
        }
        return ""
    }

**Comment by wieseljonas** [comment]
I resolved this by not reusing the main cells in the main collectionview

**Comment by SteveFortune** [comment]
Hi there.

Thanks for submitting the issue. I'm not sure about your use case but you could use 1 `UICollectionView` with some sort of custom flow, instead of embedding collection views in collection view cells. 

Anyway, I'm glad you were able to work around the problem. I'll close this issue for now - feel free to reopen the issue surfaces again.

Thanks,
Steve.
